### ISSUE TITLE
Use cbgen instead of bgen_reader

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit-bgen#20]
Based on the comments at https://github.com/limix/bgen-reader-py/issues/30 and https://github.com/pystatgen/sgkit-bgen/issues/3, it appears that @horta's https://github.com/limix/cbgen is the best upstream library for us to depend upon.

**Comment by horta** [comment]
It now supports precision specification (32 or 64 bits) and returning probabilities only: https://cbgen.readthedocs.io/en/stable/bgen_file.html#cbgen.bgen_file.read_probability

**Comment by eric-czech** [comment]
FYI this issue contains 2 things that @horta mentioned working on adding in https://github.com/limix/bgen-reader-py/issues/33. 

After that there shouldn't be much to integrating it other than switching the dependency, using the API a little differently, and wiring up the new options.

**Comment by eric-czech** [comment]
lol good timing.  Thanks @horta!

**Comment by horta** [comment]
What feature are you waiting for? Is the return of integers?

**Comment by eric-czech** [comment]
Ah no I had meant the one in https://github.com/limix/bgen-reader-py/issues/33 for skipping reads of fields like phased and ploidy.  Ohh did you mean in https://github.com/limix/bgen-reader-py/issues/33#issuecomment-686660326 that we can just read whatever fields we want individually now rather than getting a dict back with multiple of them?

**Comment by horta** [comment]
If you are going to use cbgen, I think it is ready because of https://cbgen.readthedocs.io/en/stable/bgen_file.html#cbgen.bgen_file.read_probability indeed

You will skip reading phased and ploidy.

**Comment by eric-czech** [comment]
Ok cool, I'll close out https://github.com/limix/bgen-reader-py/issues/33 then.  Thanks!

**Comment by eric-czech** [comment]
Done in https://github.com/pystatgen/sgkit/pull/314
