### ISSUE TITLE
Update bgen reader to be compatible with bgen_reader 4.0.5

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit-bgen#7]
The newest version of bgen_reader no longer works with the code we had. 

@horta do you have any suggestions on how we should rewrite this?

https://github.com/pystatgen/sgkit-bgen/blob/47a7db7f301e688d6dc828ef00404caf2d259227/sgkit_bgen/bgen_reader.py#L10

Was that hidden function renamed or removed?

Also see: https://github.com/pystatgen/sgkit-bgen/pull/4#issuecomment-673097226

**Comment by eric-czech** [comment]
Oh duh it's just [no longer hidden](https://github.com/limix/bgen-reader-py/blob/eceda00c6f34fa66882c39e210407e50f5f8ebd8/bgen_reader/_metafile.py#L70), nice!

**Comment by eric-czech** [comment]
Done in https://github.com/pystatgen/sgkit-bgen/pull/8

**Comment by horta** [comment]
Just to make some propaganda here. We shall have a Python-only bgen-reader package very soon as I release a python wrapper around the C bgen library: https://github.com/limix/cbgen-py

In fact, if anybody wants very low access to bgen files, one can simply use cbgen python package. @CarlKCarlK
